### ISSUE TITLE
[Feature] 이미지 업로드 기능

### ISSUE THREAD

**Issue by hossi97** [Team-RecruTe/Anchor-Service#10]
---
name: "✅ Feature"
about: "\U0001F449 새로운 기능에 대해 생성해주세요."
title: "[Feature] 제목을 입력해주세요"
labels: feature
assignees: ''

---

## To-Do
- [x] 이미지 도메인 설계 
- [x] 이미지 업로드 API 구현
- [x] S3 파일 업로더 구현

**Comment by hossi97** [comment]
테스트는 다음주에 작성하도록 하겠습니다.
